### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [cookieyeshq/cookieyes-gtm-template#2]
https://github.com/cookieyeshq/cookieyes-gtm-template/blob/b787b9680bfe63541d1db2e209a5f6093a543ed6/template.tpl#L116

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by jithinsk** [comment]
This issue is fixed in the latest release.
